### ISSUE TITLE
Need to bump version from v1.5.0

### ISSUE THREAD

**Issue by qub1750ul** [kt3k/deno_license_checker#6]
The instructions currently in the readme don't work
```sh
deno --allow-read --allow-run https://deno.land/x/license_checker@v1.5.0/main.ts
```
```sh
[7/8] Downloading https://deno.land/std@v0.3.1/fs/denogen/cli/bundle/compiler.js:133681:17
          return new DenoError(kind, base.error());
                 ^
Uncaught Other: Import 'https://deno.land/std@v0.3.1/fs/deno' failed: 404 Not Found
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at maybeThrowError (js/errors.ts:39:15)
    at sendSync (js/dispatch.ts:114:5)
    at fetchModuleMetaData (js/compiler.ts:137:19)
    at _resolveModule (js/compiler.ts:254:12)
    at js/compiler.ts:370:37
    at resolveModuleNames (js/compiler.ts:368:24)
    at resolveModuleNamesWorker (third_party/node_modules/typescript/lib/typescript.js:89230:127)
    at resolveModuleNamesReusingOldState (third_party/node_modules/typescript/lib/typescript.js:89473:24)
```

However, by fetching directly from master all works smoothly
```sh
deno --allow-read --allow-run https://raw.githubusercontent.com/kt3k/deno_license_checker/master/main.ts
```

**Comment by kt3k** [comment]
@qub1750ul Thank you for reporting! I did some maintainance work and pushed the tag `v1.6.0`, which should work with deno v0.11.0 (latest).
